### ISSUE TITLE
Sorting of pre-release versions

### ISSUE THREAD

**Issue by bartlannoeye** [nugot/issues#3]
Pre-release versions come before the actual release on the same version number. So following list on the package versions page
>7.0.1-beta3 pre release 2015-05-03 23,200 downloads
>7.0.1-beta2 pre release 2015-04-06 19,546 downloads
>7.0.1-beta1 pre release 2015-02-17 37,275 downloads
>7.0.1 current version 2015-06-22 398,630 downloads
>6.0.8  2015-01-11 1,406,050 downloads

should be ordered like
>7.0.1
>7.0.1-beta3
>7.0.1-beta2
>7.0.1-beta1
>6.0.8

**Comment by richorama** [comment]
Thanks for reporting this!

I'm displaying the packages in the order that the nuget API delivers them. I'll see if there's a smarter way of sorting them.

**Comment by richorama** [comment]
fixed
